/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.webbeans.config.WebBeansContext;
import org.apache.webbeans.spi.ContainerLifecycle;

public class App {
   private static ContainerLifecycle lifecycle = null;
    public static void main(String[] args)  {
        lifecycle = WebBeansContext.currentInstance().getService(ContainerLifecycle.class);
        lifecycle.startApplication(null);
        
    }

    public static void shutdown()  {
        lifecycle.stopApplication(null);
    }
    }

