/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")
    id("application")
    id("io.freefair.lombok") version "8.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    // cdi
    // https://mvnrepository.com/artifact/org.apache.openwebbeans/openwebbeans-impl
    implementation("org.apache.openwebbeans:openwebbeans-impl:4.0.2")
    // https://mvnrepository.com/artifact/org.apache.openwebbeans/openwebbeans-spi
    implementation("org.apache.openwebbeans:openwebbeans-spi:4.0.2")


    // jpa
    // https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink
    implementation("org.eclipse.persistence:eclipselink:4.0.3")

    // acceso a la base de datos
    // https://mvnrepository.com/artifact/io.helidon.webserver/helidon-webserver
    implementation("io.helidon.webserver:helidon-webserver:4.0.9")

    // json
    implementation("com.google.code.gson:gson:2.9.0")

    // base de datos incrustada
    // https://mvnrepository.com/artifact/org.xerial/sqlite-jdbc
    implementation("org.xerial:sqlite-jdbc:3.46.0.0")



}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
